### PR TITLE
Added the Documentation and formal stuff to get the github community standarts

### PR DESCRIPTION
**Pull request by foxyyyyyyyyyyyyy**
I added the following:

+ Readme Rework
+ Conrtibuting.md
+ Code of Conduct
+ Added the link to the docs in the package

### CODE REVIEW

**Comment by CalumW1** [comment]
Linked this PR to Issue #6 and #30, will review the changes sometime this week.

**Comment by foxyyyyyyyyyyyyy** [comment]
Did you had time to look at it?

**Review by CalumW1 — APPROVED** [review]
Looks like a good start. I think we spoke about it last weekend but the site will be open source? if new functionality is added then a PR will also need to be raised for doc project? Ill try and sort out a domain for it as well.

**Comment by foxyyyyyyyyyyyyy** [comment]
Yes there would be the need for a pr for the docs project too. But the docs use mdx so you can simply use markdown. If we fix the bundle size issue we can make a mono repo if you want

**Comment by foxyyyyyyyyyyyyy** [comment]
but as an monorepo I can't let my host update it automaticly because it uses github apps for that and they need to be installed to a user or organisation

**Comment by CalumW1** [comment]
> but as an monorepo I can't let my host update it automaticly because it uses github apps for that and they need to be installed to a user or organisation

Okay, i think its fine to keep them separate. ill merge this in soon.

**Pull request merged**
