### PR TITLE
added issue templates

### PR DESCRIPTION
**Pull request by foxyyyyyyyyyyyyy**
I added some issue templates to better organize new issues for demo look at my fork
https://github.com/foxyyyyyyyyyyyyy/R6StatAPI

### CODE REVIEW

**Review by CalumW1 — APPROVED** [review]
Thanks Foxy, this is a great addition. please merge in when you are ready.

**Comment by foxyyyyyyyyyyyyy** [comment]
It's ready but I don't have permission to merge it so you can merch it everytime🙂

**Comment by foxyyyyyyyyyyyyy** [comment]
The templates also auto add Tags to the issues

**Comment by CalumW1** [comment]
> It's ready but I don't have permission to merge it so you can merge it everytime🙂

Sorry didn't know that, will try and fix it.

**Comment by foxyyyyyyyyyyyyy** [comment]
Only maintainers kann merge its like this by default. Means, that only people you invited to the repo are able to do so

**Pull request merged**
